CuBoulder/tiamat10-profile

- boulder_profile.info.yml
- config/install/devel.settings.yml
- config/install/devel.toolbar.settings.yml
- config/install/system.menu.devel.yml
- config/install/user.role.architect.yml
- config/install/user.role.developer.yml
Resolves #321 - Adds redirect, migrate_plus, devel and devel permissions to D9 and D10 project templates and profiles.
Includes:
- `tiamat-project-template`
- `tiamat10-project-template`
- `tiamat10-profile`
- `tiamat-profile`
> Change: Adds Devel, Redirect, Migrate_plus required modules

- boulder_profile.links.menu.yml
- config/install/field.field.media.image.field_media_image.yml
- Decreases the weight of the home link in the main menu to a very small number (`-999`) to ensure it always appears first on the left. Resolves CuBoulder/tiamat-theme#351
- Increases the maximum image upload size from `2 MB` to `24 MB`. Resolves CuBoulder/tiamat-theme#353
Sister PR in: [tiamat-profile](https://github.com/CuBoulder/tiamat-profile/pull/46)
> Adds two minor changes

- config/install/editor.editor.full_html.yml
- config/install/editor.editor.wysiwyg.yml
- config/install/filter.format.full_html.yml
- config/install/filter.format.wysiwyg.yml
This update adds the Map plugin to CKEditor, which allows a content editor to provide a link shared from the [CU Boulder Campus Map](https://www.colorado.edu/map/) and embeds a map widget on a page. Just as in the [CKEditor 4 Shortcode](https://websupport.colorado.edu/article/425-campus-map-shortcode) there are three size options to choose from for the widget. The Map plugin outputs web component-like syntax for easier migration and future changes (see `README.md` for the schemas). CuBoulder/ucb_ckeditor_plugins#13
CuBoulder/tiamat-theme#258
Sister PR in: [ucb_ckeditor_plugins](https://github.com/CuBoulder/ucb_ckeditor_plugins/pull/15), [tiamat-profile](https://github.com/CuBoulder/tiamat-profile/pull/48)
> Adds Map plugin for embedding Campus Maps

- config/install/editor.editor.wysiwyg.yml
Removing the full justification setting option for they WYSIWYG text authoring configuration.
> Remove full justification setting for wysiwyg

- boulder_profile.info.yml
- config/install/block.block.boulder_base_breadcrumbs.yml
- config/install/block.block.boulder_base_content.yml
- config/install/block.block.boulder_base_footer_menu.yml
- config/install/block.block.boulder_base_help.yml
- config/install/block.block.boulder_base_local_actions.yml
- config/install/block.block.boulder_base_main_menu.yml
- config/install/block.block.boulder_base_messages.yml
- config/install/block.block.boulder_base_secondary_menu.yml
- config/install/block.block.site_contact_info_footer.yml
- config/install/block.block.social_media_links.yml
- config/install/system.theme.yml
CuBoulder/tiamat-theme#435
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/452), [tiamat-custom-entities](https://github.com/CuBoulder/tiamat-custom-entities/pull/70), [tiamat-profile](https://github.com/CuBoulder/tiamat-profile/pull/52), [tiamat-project-template](https://github.com/CuBoulder/tiamat-project-template/pull/28), [tiamat10-project-template](https://github.com/CuBoulder/tiamat10-project-template/pull/8), [ucb_site_configuration](https://github.com/CuBoulder/ucb_site_configuration/pull/26)
> Removes "D9" from theme name and the theme, custom entities Composer package names

- boulder_profile.info.yml
- boulder_profile.install
This update:
- Sets the site default email address in the profile at install time. CuBoulder/tiamat-theme#500
- Changes "D9" to "D10" in the Drupal module description.
> Sets site default email address in the profile

- config/install/editor.editor.wysiwyg.yml
Closes https://github.com/CuBoulder/tiamat-theme/issues/503.
Fixes ordering of the toolbar of the WYSIWYG text editor. The current missing link is the styles tab, as we currently have no styles.
> fixed wysiwyg toolbar ordering

- boulder_profile.info.yml
This update completes in-content menu blocks (menu blocks placed outside of a navigation bar, e.g. in a sidebar) by styling them and adding the [Menu Block](https://www.drupal.org/project/menu_block) contrib module for additional options.
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/552), [tiamat10-project-template](https://github.com/CuBoulder/tiamat10-project-template/pull/25), [ucb_admin_menus](https://github.com/CuBoulder/ucb_admin_menus/pull/13)
CuBoulder/tiamat-theme#267
CuBoulder/tiamat-theme#528
> Completes in-content menu blocks

- config/install/taxonomy.vocabulary.categories.yml
- config/install/user.role.architect.yml
- config/install/user.role.content_editor.yml
- config/install/user.role.developer.yml
- config/install/user.role.site_manager.yml
Removing the **_'Categories'_** taxonomy term and permissions associated with it, as all current Content Types and Blocks use the correct taxonomy term **'Category'** for terms and sorting/filtering. There were no references to the deleted **_'Categories'_** term in `ucb_custom_entities` or any other custom modules, such as `Campus News` or `Site Configuration`, only fields with a machine name that included the word 'categories", but this was only in reference to a collection of **'Category'** terms and not the actual _**'Categories'**_ term.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/587
> Remove 'Categories' taxonomy term + Associated Permissions

- boulder_profile.info.yml
- config/install/system.theme.yml
Express Admin administration sub-theme with Claro as the base theme set as the default admin theme.
> Switching to Express Admin for the administration theme

- boulder_profile.info.yml
- boulder_profile.install
- config/install/administerusersbyrole.settings.yml
- config/install/user.role.architect.yml
- config/install/user.role.developer.yml
- config/install/user.role.site_manager.yml
Allows Site Managers to configure users with an equal or lower permission level, including adding or removing roles of an equal or lower permission level.
Resolves CuBoulder/tiamat10-profile#78
Sister PR in: [tiamat10-project-template](https://github.com/CuBoulder/tiamat10-project-template/pull/33)
> Adds "Administer Users by Role" contrib module and associated configuration

- boulder_profile.info.yml
- config/install/google_tag.container.UA-105731679-1.65de22067902c7.57590325.yml
- config/install/google_tag.settings.yml
- config/install/user.role.architect.yml
- config/install/user.role.developer.yml
Adds [Google Tag](https://www.drupal.org/project/google_tag) contrib module to serve Google Analytics 4 trackers. The settings were copied over to match D7 Express. Only Architects and Developers can configure Google Tag.
Resolves CuBoulder/tiamat10-profile#90
Sister PR in: [tiamat10-project-template](https://github.com/CuBoulder/tiamat10-project-template/pull/35)
> Adds "Google Tag" contrib module

- config/install/editor.editor.wysiwyg.yml
Closes #86.
Removes some of the paste filters to accept ckeditor values. This may have negative consequences on copy-pastes from word and other text editors.
> Change paste filter to accept ckeditor values

- config/install/webform.settings.yml
- config/install/webform.webform.contact.yml
Fixes the following configuration on forms and made config changes requested by Kevin during our Site Accessibility Review:
- Disable client-side validation for all webforms
- Display required indicator on all webforms
- Use Ajax for all webforms by default
- Adds Antibot to all webforms by default
These changes and adding custom profile configuration for the default 'Contact' form allow both single and multipage forms to submit on Form Pages and Blocks
Resolves #110
> Form Configuration

- config/install/user.role.developer.yml
Sister request to https://github.com/CuBoulder/tiamat-custom-entities/pull/134.
Removes all necessary permissions for the removal of the how-to pages.
> remove how-to from permissions

- config/install/user.role.anonymous.yml
Adds the needed permission to allow anonymous users to view news feeds on the Aggregator Block. Previously the RSS feed element portion of the block would not display at all for anonymous users, causing image issues as the image part of the block would be the only part rendered.
Resolves #129
> Adds 'View News Feed' permission to Anonymous Users

- config/install/user.role.architect.yml
- config/install/user.role.content_editor.yml
- config/install/user.role.developer.yml
- config/install/user.role.edit_own_content.yml
[Change] This update adds a permission which disables access restrictions on unpublished content as well as any other content access restrictions, to the Architect and Content Editor roles. Resolves CuBoulder/tiamat10-profile#112
> Adds `bypass node access` permission to Architect and Content Editor roles

- boulder_profile.info.yml
- config/install/captcha.settings.yml
- config/install/recaptcha_v3.recaptcha_v3_action.default.yml
- config/install/recaptcha_v3.recaptcha_v3_action.default_captcha.yml
- config/install/recaptcha_v3.settings.yml
Adds config and enables on install for Captcha v3. Needs site keys for v3.
Includes:
- `profile` => https://github.com/CuBoulder/tiamat10-profile/pull/138
- `project-template` => https://github.com/CuBoulder/tiamat10-project-template/pull/45
Resolves https://github.com/CuBoulder/tiamat-theme/issues/617
> Captcha: Adds config and enables on install

- boulder_profile.info.yml
- config/install/user.role.architect.yml
- config/install/user.role.developer.yml
- config/install/user.role.site_manager.yml
This new contrib module adds a "Rebuild Cache" option in the toolbar, accessible to architects and developers. **Use this sparingly and only as a last resort after you've tried everything else, such as clearing local browser caches. A cache rebuild is an administrative action that has temporary negative effects on the performance of the site.**
Resolves CuBoulder/tiamat10-profile#147
Sister PR in: [tiamat10-project-template](https://github.com/CuBoulder/tiamat10-project-template/pull/47)
> Adds Rebuild Cache Access contrib module

- config/install/block.block.social_media_links.yml
- config/install/system.menu.footer_menu.yml
Used in conjunction with https://github.com/CuBoulder/tiamat-theme/pull/1051.
Removes the Social Media Menu Region and moves the Social Media Menu to the Footer Menu.
> Social media menu region removal

- config/install/user.role.site_manager.yml
Closes https://github.com/CuBoulder/tiamat-theme/issues/1099.
Adds the administer blocks permission, as that is layout manager's only permission to the site manager.
> Add administer blocks permission to site manager

- config/install/user.role.site_manager.yml
Closes https://github.com/CuBoulder/tiamat-theme/issues/1097.
Adds the bypass node access permission to the site manager role.
> Add permission to site manager

- config/install/google_tag.container.GTM-M3DX2QP.65de22067902c7.57590325.yml
- config/install/google_tag.settings.yml
Updaing the google tag manager code from the Universal Analytics to the newer global tag manager code. This is done in the Tag Manager module.
Site users can still put their personal codes in the GTM section of site settings.
Resolve #163
> Google Tag Update

- config/install/filter.format.full_html.yml
- config/install/filter.format.wysiwyg.yml
Adds Colorbox images to editor filters
Adds 4 new colorbox image styles: `Colorbox Small` , `Colorbox Small Square`, `Colorbox Small Thumbnail`, `Colorbox Square`. On click, these open up a modal with the full image and caption.
Includes:
- `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/1205
- `tiamat-custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/160
- `tiamat-profile` => https://github.com/CuBoulder/tiamat10-profile/pull/185
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1174
> New Image Styles: Colorbox Image Styles

- boulder_profile.info.yml
Closes https://github.com/CuBoulder/tiamat-theme/issues/629.
Adds the ncessary module for the mega menu.
> Add menu extras module

- config/install/metatag.metatag_defaults.404.yml
- config/install/metatag.metatag_defaults.front.yml
- config/install/metatag.metatag_defaults.node.yml
This update:
- [bug] Fixes meta tags missing on a site's home page but not other pages.
- [change] Resolves description meta tag to summary field instead of body field.
Resolves CuBoulder/tiamat10-profile#189
> Updates Metatag settings

- config/optional/google_tag.container.GTM-M3DX2QP.65de22067902c7.57590325.yml
The change to the optional install file should make it so only anonymous users are being tracked.
This looks to fix the admin control issues too. 
The logged in users now see youtube videos loading properly for video reveal/hero blocks. They are still sometimes broken on anonymous users.
> Tag Container Update for Anonymous only tracking

- config/install/user.role.site_manager.yml
Gives 'Site Managers' the ability to exclude content from the sitemap
Resolves https://github.com/CuBoulder/tiamat10-profile/issues/244
> #244 Site Managers: sitemap permissions to exclude content

- boulder_profile.install
- config/install/webform.settings.yml
This update turns off Ajax and resets the form config back to mostly default, so that forms aren't submitted multiple times. We are currently working on debugging multi-page form blocks which seem to have the most issues. Strongly recommended to try to keep new Webforms limited to Webform Pages or modify existing Form blocks to pages, especially the more complex multi-page forms until more is known about the issue. 
With this disabled you should also be able to enable Ajax as a per-form setting, which may help issues with complex multi-page forms. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1330
Resolves https://github.com/CuBoulder/tiamat10-profile/issues/215
> Webforms: Modify config to defauts to prevent multiple submissions

- boulder_profile.info.yml
- config/install/klaro.klaro_app.facebook.yml
- config/install/klaro.klaro_app.ga.yml
- config/install/klaro.klaro_app.gtm.yml
- config/install/klaro.klaro_app.tiktok.yml
- config/install/klaro.klaro_app.vimeo.yml
- config/install/klaro.klaro_app.youtube.yml
- config/install/klaro.settings.yml
- config/install/klaro.texts.yml
- config/install/user.role.anonymous.yml
- config/install/user.role.architect.yml
- config/install/user.role.authenticated.yml
- config/install/user.role.developer.yml
Profile and installation settings for the new Klaro! module. 
Devs and Architects have access to the settings options for Klaro
anonymous and authenticated users all needed permissions to interact with the popup.
By default klaro is looking for 
- gtm
- ga
- facebook
- tiktok
- youtube
- vimeo
Sister PR: https://github.com/CuBoulder/tiamat-theme/pull/1607
Sister PR: https://github.com/CuBoulder/tiamat10-project-template/pull/75
> Add Klaro (GDPR) Cookie manager

- boulder_profile.info.yml
- config/install/user.role.anonymous.yml
- config/install/user.role.architect.yml
- config/install/user.role.authenticated.yml
- config/install/user.role.developer.yml
- config/optional/klaro.klaro_app.facebook.yml
- config/optional/klaro.klaro_app.ga.yml
- config/optional/klaro.klaro_app.gtm.yml
- config/optional/klaro.klaro_app.tiktok.yml
- config/optional/klaro.klaro_app.vimeo.yml
- config/optional/klaro.klaro_app.youtube.yml
- config/optional/klaro.settings.yml
- config/optional/klaro.texts.yml
Klaro is in testing on the Sandbox sites but should not be enable in production.  Moving the config for that module from `config/install` to `config/optional` and setting a module dependency so that this config will be added once the module is turned on.
> Removing Klaro from the base install

- boulder_profile.info.yml
- config/install/metatag.metatag_defaults.node.yml
Previously images in Cards/Previews when sharing a site via Facebook, Twitter, Teams, etc. would not show up, despite having correct Open Graph tags. This is believed to be caused by additional url information added to the end of links, which has been adjusted to just grab the image, rather than a processed version with additional info
Includes: 
- `profile` => https://github.com/CuBoulder/tiamat10-profile/pull/280
- `custom_entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/210
Resolves #279
Resolves #277
> #279 - Using direct image file paths instead of image styles pathing for `og:image` previews

- boulder_profile.info.yml
Enables the diff module
Includes
- `profile` => https://github.com/CuBoulder/tiamat10-profile/pull/293
- `template` => https://github.com/CuBoulder/tiamat10-project-template/pull/86
- `theme` => https://github.com/CuBoulder/tiamat-theme/pull/1680
Resolves #1679 
Resolves https://github.com/CuBoulder/tiamat10-profile/issues/292
> Enables diff module
