boulder_profile.install
=> Permissions on Install Working

.github/linters/.eslintrc.yml, .github/linters/.stylelintrc.json, .github/workflows/draft-release.yml, .github/workflows/main.yml, .github/workflows/publish-release.yml, .github/workflows/update-changelog.yml, .gitignore, .vscode/settings.json, CHANGELOG.md, README.md
Resolves CuBoulder/tiamat10-profile#5 and adds a `README.md` file.
=> Adds `CHANGELOG.md`, `README.md`, and workflows to `tiamat10-profile`

boulder_profile.info.yml, config/install/filter.format.wysiwyg.yml
Added shortcodes and migration filters to the D10 profile
=> Shortcode and Migration filters

boulder_profile.install
Added new Architect to the base install profile.
=> Adding Nicole Waldrip to the default install

config/install/views.view.taxonomy_term.yml
Closes issue tiamat/theme/27.
Adds the taxonomy views
=> taxonomy implementation

boulder_profile.info.yml, config/install/metatag.metatag_defaults.403.yml, config/install/metatag.metatag_defaults.404.yml, config/install/metatag.metatag_defaults.front.yml, config/install/metatag.metatag_defaults.global.yml, config/install/metatag.metatag_defaults.node.yml, config/install/metatag.metatag_defaults.taxonomy_term.yml, config/install/metatag.metatag_defaults.user.yml, config/install/metatag.settings.yml
Closes https://github.com/CuBoulder/tiamat-theme/issues/149.
Adds profile changes for metatag installation
=> Tiamat theme/issue/149

config/install/user.role.content_editor.yml
Adding in Block permissions for the Content Editor role to resolve CuBoulder/tiamat-theme#486
=> Changing permissions for Content Editor

boulder_profile.info.yml, boulder_profile.profile
Resolves CuBoulder/tiamat-theme#488
=> Refactoring Installation of CU Default Content

config/install/views.view.content.yml
Resolves CuBoulder/tiamat-theme#505
=> Adds "Created" column to content administration page

boulder_profile.install
Closes https://github.com/CuBoulder/tiamat-theme/issues/514.
Adds the initial site manager and content editor accounts.
=> initial site manager and content editor roles

config/optional/simplesamlphp_auth.settings.yml
Added dependency to config as well.
=> Moving simplesamlphp_auth config to optional

boulder_profile.info.yml
This update:
- Adds a search modal which appears when clicking on the search icon in the top bar.
- Adds a new "Pages and search" tab to CU Boulder site settings (`/admin/config/cu-boulder/pages`). This tab contains settings accessible to Architect, Developer, and Site Manager:
- The home page setting (moved from "General").
- Options to enable site search, all of Colorado.edu search (default), both, or neither.
- Configuration for the site search label, placeholder, and URL.
- Renames "Appearance" to "Appearance and layout" and alters the descriptions of menu items.
- Adds the [Google Programmable Search Engine](https://www.drupal.org/project/google_cse) module, which allows creating custom search pages to use with site search.
CuBoulder/tiamat-theme#266
Sister PR in: …
=> Adds search frontend and settings

boulder_profile.info.yml, config/install/editor.editor.wysiwyg.yml
Closes https://github.com/CuBoulder/tiamat-theme/issues/537.
Adds profile changes necessary for the paste filter module.
=> paste filter profile change

boulder_profile.install
Adds two requested default Shortcuts:
- Blocks (admin/content/block)
- Main menu (admin/structure/menu/manage/main)
Resolves CuBoulder/tiamat10-profile#63
=> Adds default Shortcuts

boulder_profile.info.yml, config/install/user.role.developer.yml
Changing from modal to iframe modal
Sister PRs:
https://github.com/CuBoulder/tiamat-theme/pull/639
https://github.com/CuBoulder/ucb_bootstrap_layouts/pull/23
https://github.com/CuBoulder/tiamat10-project-template/pull/30
=> Modal module change

boulder_profile.info.yml, config/install/editor.editor.wysiwyg.yml, config/install/user.role.developer.yml
Added linkit to the install profile.
Updated developer permissions to handle linkit and iframe modal
Includes:
- tiamat10-project-tempate => https://github.com/CuBoulder/tiamat10-project-template/pull/32
=> Linkit and iframe modal

boulder_profile.install, config/install/block.block.boulder_base_sidebar_menu.yml
CuBoulder/tiamat-theme#633
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/650), ~~[ucb_site_configuration](https://github.com/CuBoulder/ucb_site_configuration/pull/45)~~
=> Adds sidebar menu block

config/install/block.block.boulder_base_main_menu.yml
- Expands all main menu child menu items. (CuBoulder/tiamat-theme#647)
CuBoulder/tiamat-theme#653
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/660)
=> Adds mobile menus! changes

boulder_profile.install
Resolves CuBoulder/tiamat10-profile#81
=> Updates Webform element settings

config/install/views.view.taxonomy_term.yml
Resolves CuBoulder/tiamat10-profile#88
=> Fixes Articles being duplicated on Taxonomy pages

config/install/user.role.architect.yml, config/install/user.role.content_editor.yml, config/install/user.role.site_manager.yml
Adds the administer content permission to all 4 main roles.
Resolves CuBoulder/tiamat10-profile#59
Resolves CuBoulder/tiamat10-profile#94
=> Update administer content permission

config/install/block.block.boulder_base_main_menu.yml
Displays only the root menu items. Resolves CuBoulder/tiamat10-profile#96
=> Removes child menu items from mobile menus

boulder_profile.info.yml, config/install/user.role.architect.yml, config/install/user.role.content_editor.yml, config/install/user.role.developer.yml, config/install/user.role.edit_own_content.yml, config/install/user.role.site_manager.yml
Includes:
- `profile` => https://github.com/CuBoulder/tiamat10-profile/pull/107
- `project-template` => https://github.com/CuBoulder/tiamat10-project-template/pull/39
Resolves https://github.com/CuBoulder/tiamat-theme/issues/720
=> Adds Responsive Preview on install

config/install/user.role.content_editor.yml, config/install/user.role.site_manager.yml
Removed video hero access
Users are still able to see that the item exists but they are unable to create or edit them.
Sister PR: https://github.com/CuBoulder/tiamat-theme/pull/808
=> Remove Video Hero Access

config/install/core.entity_view_display.media.image.wallpaper.yml, config/install/core.entity_view_mode.media.wallpaper.yml
Sister pull request to close https://github.com/CuBoulder/tiamat-theme/issues/804.
Adds the necessary profile changes to add wallpaper image style.
=> Issue/tiamat theme/804

config/install/field.field.media.document.field_media_document_file.yml
Resolves CuBoulder/tiamat10-profile#118
=> Updates allowed file types for the document media type

config/install/simple_sitemap.bundle_settings.default.node.basic_page.yml, config/install/simple_sitemap.bundle_settings.default.node.collection_item_page.yml, config/install/simple_sitemap.bundle_settings.default.node.form_page.yml, config/install/simple_sitemap.bundle_settings.default.node.newsletter.yml, config/install/simple_sitemap.bundle_settings.default.node.ucb_article.yml, config/install/simple_sitemap.bundle_settings.default.node.ucb_article_list.yml, config/install/simple_sitemap.bundle_settings.default.node.ucb_class_notes.yml, config/install/simple_sitemap.bundle_settings.default.node.ucb_class_notes_list_page.yml, config/install/simple_sitemap.bundle_settings.default.node.ucb_faq_page.yml, config/install/simple_sitemap.bundle_settings.default.node.ucb_issue.yml, config/install/simple_sitemap.bundle_settings.default.node.ucb_issue_archive.yml, config/install/simple_sitemap.bundle_settings.default.node.ucb_people_list_page.yml, config/install/simple_sitemap.bundle_settings.default.node.ucb_person.yml
[Change] Resolves CuBoulder/tiamat10-profile#139
=> Configures nodes to show up in XML sitemap

boulder_profile.info.yml, config/install/editor.editor.full_html.yml, config/install/editor.editor.wysiwyg.yml, config/install/filter.format.full_html.yml, config/install/filter.format.wysiwyg.yml
This update:
- Adds the [CKEditor 5 Bootstrap Accordion](https://www.drupal.org/project/ckeditor5_bootstrap_accordion) module.
- Adds the "Accordion" item to the CKEditor 5 toolbar for the WYSIWYG and Full HTML text formats.
Resolves CuBoulder/tiamat10-profile#160
Sister PR in: [tiamat10-project-template](https://github.com/CuBoulder/tiamat10-project-template/pull/48)
=> Adds the CKEditor 5 Bootstrap Accordion module

boulder_profile.info.yml, config/install/filter.format.full_html.yml, config/install/filter.format.icon_picker.yml, config/install/filter.format.wysiwyg.yml
This update:
- [Remove] Removes shortcodes from the profile. Resolves CuBoulder/tiamat10-profile#171
- [Bug] Corrects Map plugin filter out of order. Resolves CuBoulder/tiamat10-profile#169
- [Change] Enables Linkit URL Converter filter. Resolves CuBoulder/tiamat10-profile#165
=> Removes shortcodes & updates WYSIWYG settings 

config/install/filter.format.full_html.yml, config/install/filter.format.wysiwyg.yml
Includes:
- `tiamat-custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/155
- `tiamat-profile` => https://github.com/CuBoulder/tiamat10-profile/pull/177
Resolves https://github.com/CuBoulder/tiamat-custom-entities/issues/154
=> Adds new Image Style to Editor Filters

boulder_profile.info.yml
Enabling new module for Drush commands.
=> Enabling ucb_drush_commands in the profile

boulder_profile.install
Removing Nicole from the Architects list and moving Kevin from Dev to Architect by default for new sites.
=> Cleaning up default users

config/install/user.role.architect.yml, config/install/user.role.content_editor.yml, config/install/user.role.developer.yml, config/install/user.role.site_manager.yml
Closes #194.
Adds the permissions needed for Mega Menu editing.
=> Permissions for Mega Menu

config/install/user.role.architect.yml, config/install/user.role.content_editor.yml, config/install/user.role.developer.yml, config/install/user.role.site_manager.yml
[new] This update adds permissions for the Faculty Publications block.
CuBoulder/tiamat-theme#1146
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/1297), [tiamat-custom-entities](https://github.com/CuBoulder/tiamat-custom-entities/pull/172)
=> Adds permissions for the Faculty Publication block

config/install/user.role.anonymous.yml, config/install/user.role.authenticated.yml
[bug, severity:moderate] Resolves CuBoulder/tiamat10-profile#219
=> Adds Aggregator permission to authenticated users

config/install/user.role.architect.yml, config/install/user.role.content_editor.yml, config/install/user.role.developer.yml, config/install/user.role.edit_own_content.yml, config/install/user.role.site_manager.yml
This update:
- Adds permission to access help pages to fix missing help link.
[bug, severity:minor, permissions] Resolves CuBoulder/tiamat10-profile#229
=> Fixes missing help link in the admin toolbar

boulder_profile.install
=> Removing default users that no longer work here.

boulder_profile.info.yml, config/install/trash.settings.yml, config/install/user.role.architect.yml, config/install/user.role.content_editor.yml, config/install/user.role.developer.yml, config/install/user.role.site_manager.yml
Gives Site Manager roles and up the ability to restore deleted content
Includes:
- `profile` => https://github.com/CuBoulder/tiamat10-profile/pull/251
- `template` => https://github.com/CuBoulder/tiamat10-project-template/pull/71
Resolves https://github.com/CuBoulder/tiamat10-profile/issues/250
=> Adds Trash module and associated permissions

config/install/user.role.architect.yml, config/install/user.role.content_editor.yml, config/install/user.role.developer.yml, config/install/user.role.site_manager.yml
Updated role permissions for the Hero Slider
=> Update role permissions

config/install/user.role.site_manager.yml
Provides Site Managers the ability to cancel User accounts
Resolves #275
=> Site Manager: Allows cancel User

config/install/metatag.metatag_defaults.node.yml
This adds the <meta name="description" content=""> tag for SEO reasons.
Resolves #282
=> Add meta name="description"
